import type { PracticeQ } from './programTracks'

export const WEB_QUESTIONS: PracticeQ[] = [
  { question: 'What does HTML stand for?', options: ['Hyper Text Markup Language', 'Hyperlinks and Text Markup Language', 'Home Tool Markup Language'], correctIndex: 0 },
  { question: 'Who is making the Web standards?', options: ['Google', 'The World Wide Web Consortium', 'Microsoft'], correctIndex: 1 },
  { question: 'Choose the correct HTML element for the largest heading:', options: ['<h6>', '<heading>', '<h1>', '<head>'], correctIndex: 2 },
  { question: 'What is the correct HTML element for inserting a line break?', options: ['<br>', '<lb>', '<break>'], correctIndex: 0 },
  { question: 'Which character is used to indicate an end tag?', options: ['*', '<', '/', '^'], correctIndex: 2 },
  { question: 'What does CSS stand for?', options: ['Cascading Style Sheets', 'Computer Style Sheets', 'Creative Style Sheets'], correctIndex: 0 },
  { question: 'Where in an HTML document is the correct place to refer to an external style sheet?', options: ['In the <body> section', 'At the end of the document', 'In the <head> section'], correctIndex: 2 },
  { question: 'Which HTML tag is used to define an internal style sheet?', options: ['<style>', '<css>', '<script>'], correctIndex: 0 },
  { question: 'Which CSS property is used to change the background color?', options: ['bgcolor', 'color', 'background-color'], correctIndex: 2 },
  { question: 'How do you insert a comment in a CSS file?', options: ['// this is a comment //', '/* this is a comment */', '\' this is a comment'], correctIndex: 1 },
  { question: 'Inside which HTML element do we put the JavaScript?', options: ['<js>', '<javascript>', '<script>'], correctIndex: 2 },
  { question: 'How do you write "Hello World" in an alert box?', options: ['alert("Hello World");', 'msgBox("Hello World");', 'msg("Hello World");'], correctIndex: 0 },
  { question: 'How to write an IF statement in JavaScript?', options: ['if i = 5 then', 'if (i == 5)', 'if i = 5'], correctIndex: 1 },
  { question: 'How does a FOR loop start?', options: ['for (i = 0; i <= 5; i++)', 'for (i <= 5; i++)', 'for i = 1 to 5'], correctIndex: 0 },
  { question: 'What is the correct way to write a JavaScript array?', options: ['var colors = ["red", "green", "blue"]', 'var colors = 1 = ("red"), 2 = ("green")', 'var colors = (1:"red", 2:"green")'], correctIndex: 0 },
  { question: 'Which event occurs when the user clicks on an HTML element?', options: ['onmouseclick', 'onclick', 'onchange'], correctIndex: 1 },
  { question: 'How do you declare a JavaScript variable?', options: ['var carName;', 'v carName;', 'variable carName;'], correctIndex: 0 },
  { question: 'Which operator is used to assign a value to a variable?', options: ['*', '-', '='], correctIndex: 2 },
  { question: 'What will the following code return: Boolean(10 > 9)', options: ['true', 'false', 'NaN'], correctIndex: 0 },
  { question: 'Which built-in method returns the length of the string?', options: ['length()', 'size()', 'length'], correctIndex: 2 },
  { question: 'Which array method adds one or more elements to the end of an array?', options: ['last()', 'push()', 'add()'], correctIndex: 1 },
  { question: 'What does API stand for?', options: ['Application Programming Interface', 'Associated Protocol Interface', 'Advanced Program Integration'], correctIndex: 0 },
  { question: 'Which HTTP method is typically used to retrieve data?', options: ['POST', 'PUT', 'GET'], correctIndex: 2 },
  { question: 'Which status code means "Not Found"?', options: ['200', '404', '500'], correctIndex: 1 },
  { question: 'What is JSON?', options: ['Java Standard Output Network', 'JavaScript Object Notation', 'Joint System Object Node'], correctIndex: 1 },
  { question: 'What is React?', options: ['A backend framework', 'A JavaScript library for building user interfaces', 'A database engine'], correctIndex: 1 },
  { question: 'What is JSX?', options: ['A syntax extension for JavaScript', 'A new programming language', 'A database query language'], correctIndex: 0 },
  { question: 'Which React hook is used to manage state in a functional component?', options: ['useEffect', 'useState', 'useContext'], correctIndex: 1 },
  { question: 'Which hook would you use to perform a side effect after a render?', options: ['useState', 'useReducer', 'useEffect'], correctIndex: 2 },
  { question: 'What does "DOM" stand for?', options: ['Document Object Model', 'Data Object Machine', 'Display Output Management'], correctIndex: 0 },
  { question: 'Which command initiates a new Git repository?', options: ['git start', 'git init', 'git create'], correctIndex: 1 },
  { question: 'How do you check the current state of a Git repository?', options: ['git info', 'git state', 'git status'], correctIndex: 2 },
  { question: 'What is a "Promise" in JavaScript?', options: ['An object representing the eventual completion of an async operation', 'A guarantee that the code has no bugs', 'A keyword used to declare a variable'], correctIndex: 0 },
  { question: 'What does the spread operator (...) do in JavaScript?', options: ['Expands an iterable into more elements', 'Sums up all elements in an array', 'Copies a string strictly'], correctIndex: 0 },
  { question: 'In Node.js, what does the require() function do?', options: ['Deletes a file', 'Imports a module', 'Requires a password'], correctIndex: 1 },
  { question: 'What is Express.js primarily used for?', options: ['Building the frontend UI', 'Writing CSS', 'Building web applications and APIs in Node.js'], correctIndex: 2 },
  { question: 'Which property in CSS creates space *inside* an element\'s border?', options: ['padding', 'margin', 'spacing'], correctIndex: 0 },
  { question: 'What does NPM stand for?', options: ['Node Package Manager', 'New Programming Module', 'Non Process Memory'], correctIndex: 0 },
  { question: 'What is the purpose of CORS?', options: ['It styles the page', 'It limits which origins can access a server resource', 'It is a database format'], correctIndex: 1 },
  { question: 'Which SQL statement is used to extract data from a database?', options: ['GET', 'EXTRACT', 'SELECT'], correctIndex: 2 },
]

export const DATA_QUESTIONS: PracticeQ[] = [
  { question: 'What does SQL stand for?', options: ['Strong Question Language', 'Structured Query Language', 'Structured Question Language'], correctIndex: 1 },
  { question: 'Which SQL statement is used to update data in a database?', options: ['UPDATE', 'MODIFY', 'SAVE AS'], correctIndex: 0 },
  { question: 'Which SQL statement is used to delete data from a database?', options: ['REMOVE', 'COLLAPSE', 'DELETE'], correctIndex: 2 },
  { question: 'Which SQL statement is used to insert new data in a database?', options: ['ADD RECORD', 'INSERT INTO', 'ADD TO'], correctIndex: 1 },
  { question: 'With SQL, how do you select all columns from a table named "Persons"?', options: ['SELECT * FROM Persons', 'SELECT Persons', 'SELECT [all] FROM Persons'], correctIndex: 0 },
  { question: 'With SQL, how do you select a column named "FirstName" from "Persons"?', options: ['EXTRACT FirstName FROM Persons', 'SELECT FirstName FROM Persons', 'GET FirstName FROM Persons'], correctIndex: 1 },
  { question: 'Which SQL clause is used to filter records?', options: ['FILTER', 'WHERE', 'ORDER BY'], correctIndex: 1 },
  { question: 'With SQL, how can you return all records where "FirstName" is "Peter"?', options: ['SELECT * FROM Persons WHERE FirstName=\'Peter\'', 'SELECT * FROM Persons WHERE FirstName<>\'Peter\'', 'SELECT [all] FROM Persons WHERE FirstName LIKE \'Peter\''], correctIndex: 0 },
  { question: 'What is the most common JOIN used to merge rows based on a matching column?', options: ['FULL JOIN', 'INNER JOIN', 'CROSS JOIN'], correctIndex: 1 },
  { question: 'Which function is used to count the number of rows in a SQL result?', options: ['TOTAL()', 'SUM()', 'COUNT()'], correctIndex: 2 },
  { question: 'In Excel/spreadsheets, what is the purpose of a VLOOKUP function?', options: ['To format cells vertically', 'To search for a value in the first column and return a value in the same row', 'To add multiple conditions together'], correctIndex: 1 },
  { question: 'What is a Pivot Table primarily used for?', options: ['To create 3D animations', 'To quickly summarize and analyze large amounts of data', 'To validate email addresses'], correctIndex: 1 },
  { question: 'What does KPI stand for?', options: ['Key Performance Indicator', 'Known Problem Identification', 'Key Product Insight'], correctIndex: 0 },
  { question: 'Which metric usually represents the percentage of visitors who leave after viewing only one page?', options: ['Churn Rate', 'Bounce Rate', 'Click-through Rate'], correctIndex: 1 },
  { question: 'What is A/B testing?', options: ['A test done blindly', 'Comparing two versions of a webpage to see which performs better', 'Testing alpha and beta software'], correctIndex: 1 },
  { question: 'What is the median of a dataset?', options: ['The most frequent value', 'The average value', 'The middle value when sorted'], correctIndex: 2 },
  { question: 'If data is heavily skewed by a few massive outliers, which average measure is best to use?', options: ['Mean', 'Median', 'Mode'], correctIndex: 1 },
  { question: 'What does ETL stand for in the context of data warehouses?', options: ['External Text Language', 'Export Target Load', 'Extract, Transform, Load'], correctIndex: 2 },
  { question: 'Which is a primary key?', options: ['A column that uniquely identifies each row in a table', 'The most important table in a database', 'The first column of any table'], correctIndex: 0 },
  { question: 'What is the role of a data visualization tool like Tableau or PowerBI?', options: ['To write backend server logic', 'To present data visually so insights are easily understandable', 'To secure a database'], correctIndex: 1 },
  { question: 'What does "CAC" commonly stand for in business analytics?', options: ['Customer Acquisition Cost', 'Center for Analytics Control', 'Core Annual Compounding'], correctIndex: 0 },
  { question: 'Which chart type is best used to show a trend over time?', options: ['Pie Chart', 'Line Chart', 'Scatter Plot'], correctIndex: 1 },
  { question: 'Which chart is strictly used for showing parts of a whole (though often discouraged by data scientists)?', options: ['Histogram', 'Line Chart', 'Pie Chart'], correctIndex: 2 },
  { question: 'What does the term "Data Cleansing" imply?', options: ['Deleting the entire database', 'Identifying and correcting inaccurate or corrupt records', 'Organizing files on a desktop'], correctIndex: 1 },
  { question: 'What is an outlier?', options: ['A user who uninstalls the app', 'A data point that differs significantly from other observations', 'A column without an index'], correctIndex: 1 },
  { question: 'What is standard deviation?', options: ['A measure of the amount of variation or dispersion of a set of values', 'The literal difference between the max and min of an array', 'A way to format times dates'], correctIndex: 0 },
  { question: 'What does CTR stand for?', options: ['Click-Through Rate', 'Cost To Return', 'Call Tracking Ratio'], correctIndex: 0 },
  { question: 'What is a common metric to track subscriptions ending or being cancelled?', options: ['LTV', 'Churn Rate', 'Conversion Rate'], correctIndex: 1 },
  { question: 'What does LTV (or CLTV) stand for?', options: ['Lifetime Value (Customer Lifetime Value)', 'Least Tangible Variable', 'Local Time Variability'], correctIndex: 0 },
  { question: 'What is qualitative data?', options: ['Data expressed as numbers', 'Data expressing subjective properties and descriptors', 'A type of database'], correctIndex: 1 },
  { question: 'What is quantitative data?', options: ['Data expressing subjective properties', 'Data dealing with numbers and things that can be measured objectively', 'Textual user reviews'], correctIndex: 1 },
  { question: 'Which language is most popular alongside SQL for advanced data analysis and machine learning?', options: ['Python', 'HTML', 'CSS'], correctIndex: 0 },
  { question: 'What is a Null value in SQL?', options: ['Zero', 'A space character', 'A field with no value'], correctIndex: 2 },
  { question: 'What does the GROUP BY statement do?', options: ['Sorts the results alphabetically', 'Groups rows that have the same values into summary rows', 'Deletes duplicate rows'], correctIndex: 1 },
  { question: 'Which clause is used to filter records after a GROUP BY is applied?', options: ['WHERE', 'HAVING', 'FILTER'], correctIndex: 1 },
  { question: 'What does ROI stand for?', options: ['Return on Investment', 'Rate of Inference', 'Report of Insights'], correctIndex: 0 },
  { question: 'What is a dashboard?', options: ['An API server endpoint', 'A physical board for notes', 'A view showcasing KPIs and metrics in one place'], correctIndex: 2 },
  { question: 'What is a funnel analysis?', options: ['Tracing how fluids move', 'Analyzing the steps users take to complete a goal', 'Calculating geometric volumes'], correctIndex: 1 },
  { question: 'Which library is extremely popular for data manipulation in Python?', options: ['React', 'Pandas', 'Express'], correctIndex: 1 },
  { question: 'What is the primary language used to request data from relational databases?', options: ['JavaScript', 'HTML', 'SQL'], correctIndex: 2 },
]
